#pragma once

// =============================================================================
// Novis native backend — emit C++, compile with clang++.
// =============================================================================
// The interpreter is fine for bootstrapping. Real speed comes from lowering
// the AST to C++ and shelling out to clang++ to produce a native binary. The
// generated C++ includes the header-only runtime in `src/nv_runtime.h` so the
// binary has zero Python and zero external deps.

#include <cstdlib>
#include <cstdio>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>
#include <memory>
#include <utility>
#include <stdexcept>
#include <algorithm>
#include <set>
#include <map>
#include <unistd.h>
#include <sys/stat.h>

#include "ast.h"
#include "evaluator.h"
#include "lexer.h"
#include "parser.h"
#include "typechecker.h"

class NativeCompiler {
public:
    std::string compile(const std::vector<std::unique_ptr<Stmt>>& program,
                        const std::string& source_path) {
        path_ = source_path;
        out_.str("");
        out_.clear();
        local_counter_ = 0;
        temp_counter_ = 0;
        in_function_ = false;
        functions_.clear();
        function_order_.clear();

        discover(program);

        out_ << "// Generated by Novis native backend from " << source_path << "\n";
        out_ << "#include \"evaluator.h\"\n";
        out_ << "#include \"nv_runtime.h\"\n\n";
        out_ << "using namespace nvrt;\n\n";

        for (const auto& name : function_order_) {
            out_ << "Value nvf_" << name << "(";
            const FunctionDeclStmt& fn = *functions_[name];
            for (std::size_t i = 0; i < fn.params.size(); ++i) {
                if (i) out_ << ", ";
                out_ << "Value";
            }
            out_ << ");\n";
        }
        out_ << "\n";

        for (const auto& name : function_order_) {
            emit_function(functions_[name]);
            out_ << "\n";
        }

        out_ << "int main() {\n";
        in_function_ = false;
        locals_.clear();
        local_counter_ = 0;
        for (const auto& stmt : program) {
            if (dynamic_cast<FunctionDeclStmt*>(stmt.get())) continue;
            if (dynamic_cast<TypeDeclStmt*>(stmt.get())) continue;
            if (dynamic_cast<InterfaceDeclStmt*>(stmt.get())) continue;
            emit_stmt(stmt.get());
        }
        out_ << "  return 0;\n";
        out_ << "}\n";

        return out_.str();
    }

private:
    std::ostringstream out_;
    std::string path_;
    bool in_function_ = false;
    int local_counter_ = 0;
    int temp_counter_ = 0;

    std::map<std::string, std::string> locals_;
    std::map<std::string, FunctionDeclStmt*> functions_;
    std::vector<std::string> function_order_;

    void discover(const std::vector<std::unique_ptr<Stmt>>& program) {
        std::set<std::string> emitted;
        // First pass: collect all functions.
        for (const auto& stmt : program) {
            if (auto fn = dynamic_cast<FunctionDeclStmt*>(stmt.get())) {
                if (functions_.count(fn->name))
                    throw std::runtime_error("duplicate function '" + fn->name + "'");
                functions_[fn->name] = fn;
            }
        }
        // Second pass: topological order, then remaining (mutual recursion) in declaration order.
        std::set<std::string> declared;
        for (const auto& stmt : program) {
            if (auto fn = dynamic_cast<FunctionDeclStmt*>(stmt.get())) declared.insert(fn->name);
        }
        bool progress = true;
        while (progress) {
            progress = false;
            for (const auto& name : declared) {
                if (emitted.count(name)) continue;
                if (can_emit(name, emitted)) {
                    function_order_.push_back(name);
                    emitted.insert(name);
                    progress = true;
                }
            }
        }
        for (const auto& stmt : program) {
            if (auto fn = dynamic_cast<FunctionDeclStmt*>(stmt.get())) {
                if (!emitted.count(fn->name)) {
                    function_order_.push_back(fn->name);
                    emitted.insert(fn->name);
                }
            }
        }
    }

    bool can_emit(const std::string& name, const std::set<std::string>& emitted) {
        FunctionDeclStmt* fn = functions_[name];
        for (const auto& stmt : collect_stmts(fn->body.get())) {
            std::vector<CallExpr*> calls;
            collect_calls(stmt.get(), calls);
            for (const auto& c : calls) {
                if (auto v = dynamic_cast<VariableExpr*>(c->callee.get())) {
                    if (functions_.count(v->name) && !emitted.count(v->name)) return false;
                }
            }
        }
        return true;
    }

    void collect_calls(Stmt* s, std::vector<CallExpr*>& out) {
        if (auto es = dynamic_cast<ExprStmt*>(s)) collect_calls_expr(es->expr.get(), out);
        else if (auto rs = dynamic_cast<ReturnStmt*>(s)) collect_calls_expr(rs->value.get(), out);
        else if (auto vd = dynamic_cast<VarDeclStmt*>(s)) if (vd->init) collect_calls_expr(vd->init.get(), out);
        else if (auto bs = dynamic_cast<BlockStmt*>(s)) for (const auto& c : bs->statements) collect_calls(c.get(), out);
        else if (auto is = dynamic_cast<IfStmt*>(s)) {
            collect_calls_expr(is->condition.get(), out);
            collect_calls(is->then_branch.get(), out);
            if (is->else_branch) collect_calls(is->else_branch.get(), out);
        } else if (auto ws = dynamic_cast<WhileStmt*>(s)) {
            collect_calls_expr(ws->condition.get(), out);
            collect_calls(ws->body.get(), out);
        }
    }

    void collect_calls_expr(Expr* e, std::vector<CallExpr*>& out) {
        if (!e) return;
        if (auto c = dynamic_cast<CallExpr*>(e)) out.push_back(c);
        else if (auto b = dynamic_cast<BinaryExpr*>(e)) {
            collect_calls_expr(b->lhs.get(), out);
            collect_calls_expr(b->rhs.get(), out);
        } else if (auto u = dynamic_cast<UnaryExpr*>(e)) collect_calls_expr(u->operand.get(), out);
        else if (auto ce = dynamic_cast<CallExpr*>(e)) out.push_back(ce);
    }

    std::vector<std::unique_ptr<Stmt>> empty_stmts;
    std::vector<std::unique_ptr<Stmt>>& collect_stmts(Stmt* s) {
        if (auto bs = dynamic_cast<BlockStmt*>(s)) return bs->statements;
        empty_stmts.clear();
        if (s) empty_stmts.push_back(std::unique_ptr<Stmt>(s));
        return empty_stmts;
    }

    std::string fresh_local() { return "_v" + std::to_string(local_counter_++); }
    std::string fresh_temp()  { return "_t" + std::to_string(temp_counter_++); }

    void emit(const std::string& line) { out_ << "  " << line << "\n"; }

    static std::string escape_cpp_string(const std::string& s) {
        std::string out;
        out.reserve(s.size() + 2);
        out.push_back('"');
        for (char c : s) {
            switch (c) {
                case '\n': out += "\\n"; break;
                case '\t': out += "\\t"; break;
                case '\\': out += "\\\\"; break;
                case '"':  out += "\\\""; break;
                default:   out.push_back(c); break;
            }
        }
        out.push_back('"');
        return out;
    }

    static std::string type_to_native_cpp(const TypeAnnotation* t) {
        if (!t) return "Value";
        switch (t->kind) {
            case TypeAnnotation::Kind::Int:     return "int64_t";
            case TypeAnnotation::Kind::Float32: return "double";
            case TypeAnnotation::Kind::Str:     return "std::string";
            case TypeAnnotation::Kind::Bool:    return "bool";
            case TypeAnnotation::Kind::Decimal: return "Decimal";
            case TypeAnnotation::Kind::Money:   return "Money";
            case TypeAnnotation::Kind::Tensor:  return "Tensor";
            case TypeAnnotation::Kind::Custom:  return "Value";
        }
        return "Value";
    }

    void emit_stmt(Stmt* stmt) {
        if (auto vd = dynamic_cast<VarDeclStmt*>(stmt))  return emit_vardecl(vd);
        if (auto es = dynamic_cast<ExprStmt*>(stmt))    return emit_exprstmt(es);
        if (auto bs = dynamic_cast<BlockStmt*>(stmt))    return emit_block(bs);
        if (auto is = dynamic_cast<IfStmt*>(stmt))      return emit_if(is);
        if (auto ws = dynamic_cast<WhileStmt*>(stmt))   return emit_while(ws);
        if (auto rs = dynamic_cast<ReturnStmt*>(stmt))  return emit_return(rs);
        throw std::runtime_error("unsupported statement in native backend");
    }

    void emit_vardecl(VarDeclStmt* s) {
        std::string slot = fresh_local();
        std::string rhs = emit_expr(s->init.get());
        std::string ctype = s->type ? type_to_native_cpp(s->type.get()) : expr_native_cpp(s->init.get());
        locals_[s->name] = slot;
        emit(ctype + " " + slot + " = " + native_value(ctype, rhs) + ";");
    }

    void emit_exprstmt(ExprStmt* s) {
        std::string v = emit_expr(s->expr.get());
        emit(v + ";");
    }

    void emit_block(BlockStmt* s) {
        for (const auto& child : s->statements) emit_stmt(child.get());
    }

    void emit_if(IfStmt* s) {
        std::string cond = emit_expr(s->condition.get());
        emit("if (nv_truthy(" + cond + ")) {");
        emit_stmt(s->then_branch.get());
        if (s->else_branch) {
            emit("} else {");
            emit_stmt(s->else_branch.get());
        }
        emit("}");
    }

    void emit_while(WhileStmt* s) {
        emit("while (true) {");
        emit("if (!nv_truthy(" + emit_expr(s->condition.get()) + ")) break;");
        emit_stmt(s->body.get());
        emit("}");
    }

    void emit_return(ReturnStmt* s) {
        if (s->value) emit("return " + emit_expr(s->value.get()) + ";");
        else          emit("return nv_ctors::make_int(0);");
    }

    void emit_function(FunctionDeclStmt* fn) {
        in_function_ = true;
        locals_.clear();
        local_counter_ = 0;

        out_ << "Value nvf_" << fn->name << "(";
        for (std::size_t i = 0; i < fn->params.size(); ++i) {
            if (i) out_ << ", ";
            std::string slot = "_p" + std::to_string(i);
            locals_[fn->params[i].name] = slot;
            out_ << "Value " << slot;
        }
        out_ << ") {\n";

        if (auto block = dynamic_cast<BlockStmt*>(fn->body.get())) {
            for (const auto& stmt : block->statements) emit_stmt(stmt.get());
        }
        out_ << "  return nv_ctors::make_int(0);\n";
        out_ << "}\n";
        in_function_ = false;
    }

    std::string emit_expr(Expr* expr) {
        if (auto il = dynamic_cast<IntLiteral*>(expr)) {
            return "nv_ctors::make_int(" + std::to_string(il->value) + ")";
        }
        if (auto fl = dynamic_cast<FloatLiteral*>(expr)) {
            std::ostringstream ss; ss << fl->value; return "nv_ctors::make_double(" + ss.str() + ")";
        }
        if (auto sl = dynamic_cast<StringLiteral*>(expr)) {
            return "nv_ctors::make_string(" + escape_cpp_string(sl->value) + ")";
        }
        if (auto bl = dynamic_cast<BoolLiteral*>(expr)) {
            return std::string("nv_ctors::make_bool(") + (bl->value ? "true" : "false") + ")";
        }
        if (auto tl = dynamic_cast<TensorLiteral*>(expr)) {
            return emit_tensor_literal(tl);
        }
        if (auto v = dynamic_cast<VariableExpr*>(expr)) {
            auto lit = locals_.find(v->name);
            if (lit != locals_.end()) return "nv_ctors::make_from(" + lit->second + ")";
            if (functions_.count(v->name)) return "nv_ctors::make_from(static_cast<int64_t>(0))"; // placeholder
            throw std::runtime_error("undefined variable '" + v->name + "' in native backend");
        }
        if (auto b = dynamic_cast<BinaryExpr*>(expr)) return emit_binary(b);
        if (auto u = dynamic_cast<UnaryExpr*>(expr)) return emit_unary(u);
        if (auto c = dynamic_cast<CallExpr*>(expr)) return emit_call(c);
        if (auto a = dynamic_cast<AssignExpr*>(expr)) return emit_assign(a);
        throw std::runtime_error("unsupported expression in native backend");
    }

    std::string emit_tensor_literal(TensorLiteral* t) {
        // For small literals, inline each element as a Value. For large literals
        // (>= 256 elements), emit a raw static double array. The Value-wrapper
        // path is slow to compile for big literals.
        const std::size_t threshold = 256;
        std::ostringstream ss;
        if (t->elements.size() < threshold) {
            ss << "([](){ Tensor tt; tt.shape = {" << t->elements.size() << "}; tt.data = {";
            for (std::size_t i = 0; i < t->elements.size(); ++i) {
                if (i) ss << ", ";
                ss << nv_to_double(emit_expr(t->elements[i].get()));
            }
            ss << "}; return tt; }())";
        } else {
            // Raw numeric path: build a static array of doubles, then wrap.
            // Only works if every element is a numeric literal (int or float).
            // Non-literal elements fall back to the inline path.
            bool all_literal = true;
            for (const auto& el : t->elements) {
                if (!dynamic_cast<IntLiteral*>(el.get()) &&
                    !dynamic_cast<FloatLiteral*>(el.get())) {
                    all_literal = false;
                    break;
                }
            }
            if (all_literal) {
                int arr_id = tensor_arr_counter_++;
                ss << "([](){ static const double _tv" << arr_id << "[] = {";
                for (std::size_t i = 0; i < t->elements.size(); ++i) {
                    if (i) ss << ", ";
                    if (auto il = dynamic_cast<IntLiteral*>(t->elements[i].get())) {
                        ss << il->value << ".0";
                    } else if (auto fl = dynamic_cast<FloatLiteral*>(t->elements[i].get())) {
                        ss << fl->value;
                    }
                }
                ss << "}; Tensor tt; tt.shape = {" << t->elements.size()
                   << "}; tt.data.assign(_tv" << arr_id << ", _tv" << arr_id
                   << " + " << t->elements.size() << "); return tt; }())";
            } else {
                ss << "([](){ Tensor tt; tt.shape = {" << t->elements.size() << "}; tt.data = {";
                for (std::size_t i = 0; i < t->elements.size(); ++i) {
                    if (i) ss << ", ";
                    ss << nv_to_double(emit_expr(t->elements[i].get()));
                }
                ss << "}; return tt; }())";
            }
        }
        return ss.str();
    }

    int tensor_arr_counter_ = 0;

    static std::string nv_to_double(const std::string& v) {
        return "nv_to_double(" + v + ")";
    }

    std::string emit_binary(BinaryExpr* e) {
        std::string op;
        switch (e->op) {
            case BinOp::Add: op = "nv_add"; break;
            case BinOp::Sub: op = "nv_sub"; break;
            case BinOp::Mul: op = "nv_mul"; break;
            case BinOp::Div: op = "nv_div"; break;
            case BinOp::Mod: op = "nv_mod"; break;
            case BinOp::Eq:  op = "nv_eq";  break;
            case BinOp::Neq: op = "nv_neq"; break;
            case BinOp::Lt:  op = "nv_lt";  break;
            case BinOp::Gt:  op = "nv_gt";  break;
            case BinOp::Lte: op = "nv_lte"; break;
            case BinOp::Gte: op = "nv_gte"; break;
            case BinOp::And: op = "nv_and"; break;
            case BinOp::Or:  op = "nv_or";  break;
        }
        std::string a = emit_expr(e->lhs.get());
        std::string b = emit_expr(e->rhs.get());
        return std::string("(") + op + "(" + a + ", " + b + "))";
    }

    std::string emit_unary(UnaryExpr* e) {
        std::string v = emit_expr(e->operand.get());
        if (e->op == UnaryOp::Neg) return std::string("(nv_neg(") + v + "))";
        return std::string("(nv_not(") + v + "))";
    }

    std::string emit_call(CallExpr* e) {
        if (auto var = dynamic_cast<VariableExpr*>(e->callee.get())) {
            const std::string& name = var->name;
            if (name == "print")  return "nv_print(" + emit_expr(e->args[0].get()) + ")";
            if (name == "len")    return "nv_len(" + emit_expr(e->args[0].get()) + ")";
            if (name == "sum" || name == "mean" || name == "variance" ||
                name == "stddev" || name == "min" || name == "max")
                return std::string("nv_") + name + "(" + emit_expr(e->args[0].get()) + ")";
            if (name == "dot")
                return "nv_dot(" + emit_expr(e->args[0].get()) + ", " + emit_expr(e->args[1].get()) + ")";
            if (name == "relu" || name == "softmax" || name == "sigmoid" || name == "argmax")
                return std::string("nv_") + name + "(" + emit_expr(e->args[0].get()) + ")";
            if (name == "money") {
                std::ostringstream ss;
                ss << "nv_money(" << emit_expr(e->args[0].get());
                if (e->args.size() >= 2) ss << ", " << emit_expr(e->args[1].get());
                ss << ")"; return ss.str();
            }
            if (name == "decimal") return "nv_decimal(" + emit_expr(e->args[0].get()) + ")";
            if (name == "round_bankers") {
                std::ostringstream ss;
                ss << "nv_round_bankers(" << emit_expr(e->args[0].get());
                if (e->args.size() >= 2) ss << ", (int)" << emit_expr(e->args[1].get());
                ss << ")"; return ss.str();
            }
            if (name == "is_balanced") {
                std::ostringstream ss;
                ss << "nv_is_balanced(std::vector<Value>{";
                for (std::size_t i = 0; i < e->args.size(); ++i) {
                    if (i) ss << ", ";
                    ss << emit_expr(e->args[i].get());
                }
                ss << "})"; return ss.str();
            }
            if (name == "Tensor" || name == "tensor") {
                std::ostringstream ss;
                ss << "nv_tensor(std::vector<Value>{";
                for (std::size_t i = 0; i < e->args.size(); ++i) {
                    if (i) ss << ", ";
                    ss << emit_expr(e->args[i].get());
                }
                ss << "})"; return ss.str();
            }
            if (name == "sqrt")
                return "nv_sqrt(" + emit_expr(e->args[0].get()) + ")";
            if (name == "pow")
                return "nv_pow(" + emit_expr(e->args[0].get()) + ", " + emit_expr(e->args[1].get()) + ")";
            if (name == "read_text")
                return "nv_read_text(" + emit_expr(e->args[0].get()) + ")";
            if (name == "write_text")
                return "nv_write_text(" + emit_expr(e->args[0].get()) + ", " + emit_expr(e->args[1].get()) + ")";
            if (name == "currency")
                return "nv_currency(" + emit_expr(e->args[0].get()) + ")";
            if (name == "shape")
                return "nv_shape(" + emit_expr(e->args[0].get()) + ")";
            if (name == "risk_score")
                return "nv_risk_score(" + emit_expr(e->args[0].get()) + ")";
            if (functions_.count(name)) {
                std::ostringstream ss;
                ss << "nvf_" << name << "(";
                for (std::size_t i = 0; i < e->args.size(); ++i) {
                    if (i) ss << ", ";
                    ss << emit_expr(e->args[i].get());
                }
                ss << ")";
                return ss.str();
            }
        }
        throw std::runtime_error("unsupported call in native backend");
    }

    std::string emit_assign(AssignExpr* e) {
        std::string rhs = emit_expr(e->value.get());
        auto lit = locals_.find(e->name);
        if (lit != locals_.end()) {
            emit(lit->second + " = " + native_value(lit->second, rhs) + ";");
            return rhs;
        }
        // Implicit declaration on first assignment (matches the interpreter
        // behaviour for `x = expr` at expression-statement level).
        std::string slot = fresh_local();
        locals_[e->name] = slot;
        std::string ctype = expr_native_cpp(e->value.get());
        if (ctype == "Value") {
            emit("Value " + slot + " = " + rhs + ";");
        } else {
            // If RHS is a Value, unwrap via nv_to_double where appropriate.
            emit(ctype + " " + slot + " = nv_to_double(" + rhs + ");");
        }
        return rhs;
    }

    static std::string expr_native_cpp(Expr* e) {
        if (dynamic_cast<IntLiteral*>(e))    return "int64_t";
        if (dynamic_cast<FloatLiteral*>(e))  return "double";
        if (dynamic_cast<StringLiteral*>(e)) return "std::string";
        if (dynamic_cast<BoolLiteral*>(e))   return "bool";
        if (dynamic_cast<TensorLiteral*>(e)) return "Tensor";
        return "Value";
    }

    std::string native_value(const std::string& ctype, const std::string& value_expr) const {
        if (ctype == "int64_t")  return "static_cast<int64_t>(nv_to_double(" + value_expr + "))";
        if (ctype == "double")   return "nv_to_double(" + value_expr + ")";
        if (ctype == "bool")     return "nv_truthy(" + value_expr + ")";
        if (ctype == "std::string") return "nv_to_string(" + value_expr + ")";
        return value_expr;
    }
};

class NativeDriver {
public:
    static std::string build(const std::string& source,
                             const std::string& source_path) {
        Lexer lex(source);
        auto tokens = lex.tokenize();
        Parser parser(std::move(tokens));
        auto program = parser.parse_program();
        TypeChecker checker;
        checker.check(program);

        NativeCompiler compiler;
        std::string cpp = compiler.compile(program, source_path);

        char tmpl[] = "/tmp/novis_src_XXXXXX.cpp";
        int fd = mkstemps(tmpl, 4);
        if (fd < 0) throw std::runtime_error("mkstemp failed");
        close(fd);
        std::string src_path = tmpl;
        std::ofstream out(src_path);
        out << cpp;
        out.close();

        char bin_tmpl[] = "/tmp/novis_bin_XXXXXX";
        fd = mkstemp(bin_tmpl);
        if (fd < 0) throw std::runtime_error("mkstemp failed");
        close(fd);
        std::string bin_path = bin_tmpl;

        std::string cmd = "clang++ -std=c++17 -O2 -Isrc -o " + bin_path + " " + src_path + " 2>&1";
        FILE* pipe = popen(cmd.c_str(), "r");
        if (!pipe) throw std::runtime_error("popen failed");
        std::string compiler_output;
        char buf[1024];
        while (std::fgets(buf, sizeof(buf), pipe)) compiler_output += buf;
        int rc = pclose(pipe);
        if (rc != 0) {
            throw std::runtime_error("native compile failed:\n" + compiler_output);
        }
        return bin_path;
    }
};
